# decrypt deployment private key
before_install:
  - openssl aes-256-cbc -K $encrypted_f3556f82c616_key -iv $encrypted_f3556f82c616_iv -in arborchurch-travis.enc -out arborchurch-travis -d

# install hugo
install:
  - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb
  - dpkg -i hugo_0.17-64bit.deb

# build the site
script: 
  - hugo --theme=arbor

# deploy it!
after_success:
  - cd public
  - scp -i arborchurch-travis -r * arborchurch@arborchurchnw.org:arborchurchnw.org

