# decrypt deployment private key
before_install:
  - openssl aes-256-cbc -K $encrypted_f3556f82c616_key -iv $encrypted_f3556f82c616_iv -in arborchurch-travis.enc -out arborchurch-travis -d
  - chmod 0600 arborchurch-travis

# only deploy the master branch
branches: 
  only:
    - master

# install hugo
install:
  - wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz
  - tar xzvf hugo_0.18.1_Linux-64bit.tar.gz

# build the site
script: 
  - cd site
  - ../hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 --baseURL=https://www.arborchurch.com/ --theme=arbor

# deploy it!
after_success:
  - rsync -cav -s 'ssh -i ../../arborchurch-travis -o StrictHostKeyChecking=no' --progress public/ arborchurch@arborchurch.com:arborchurch.com

